// This file is generated by scripts/generate-i18n-types.mjs.
// Do not edit it manually.

export type Resources = {
  translation: {
    header: {
      closeMenu: 'Close navigation menu';
      languageSwitcher: {
        label: 'Choose language';
        language: {
          en: 'EN';
          pt: 'PT';
        };
      };
      navigation: {
        about: 'About';
        contact: 'Contact';
        experience: 'Experience';
        projects: 'Projects';
      };
      navigationLabel: 'Primary navigation';
      openMenu: 'Open navigation menu';
    };
    hero: {
      cta: 'View my work';
      description: 'React, TypeScript and frontend experience in the crypto industry.';
      headline: 'Sammuel Reis';
      projects: {
        github: 'GitHub';
        liveProject: 'Live project';
      };
      role: 'Frontend Developer';
      scrollIndicator: 'Scroll to continue';
    };
    projects: {
      manaVaultBuilder: {
        imageAlt: 'ManaVaultBuilder project thumbnail';
        title: 'ManaVaultBuilder';
      };
      nfEtMatcher: {
        imageAlt: 'NF_ET Matcher project thumbnail';
        title: 'NF_ET Matcher';
      };
    };
  };
};
