// This file is generated by scripts/generate-i18n-types.mjs.
// Do not edit it manually.

export type Resources = {
  translation: {
    experience: {
      mainAreas: 'Main areas';
      ripio: {
        area: {
          backoffice: 'Backoffice and internal administrative tools';
          designSystem: 'Design systems and reusable components with Storybook';
          internationalization: 'Internationalization (i18n)';
          performance: 'Performance and legacy browser compatibility';
          testing: 'Unit, integration and end-to-end testing';
          trading: 'Trading interfaces, TradingView charts and WebSocket-powered order book';
        };
        companyType: 'Crypto exchange';
        description: 'Built and maintained frontend applications for a crypto exchange, spanning trading, backoffice, shared UI foundations and SEO-oriented landing pages. Worked with real-time market data, automated testing, internationalization, performance and legacy browser compatibility.';
        period: 'Dec 2021 - Jan 2025';
        role: 'Frontend Developer';
      };
      technologies: 'Technologies';
      title: 'Experience';
      weAccelerate: {
        area: {
          backend: 'REST APIs and backend services with Node.js, Express and MongoDB';
          integrations: 'Firebase authentication, notifications and geolocation';
          mobile: 'Cross-platform mobile applications with React Native';
          realtime: 'Real-time chat features and Redis caching';
          web: 'React and TypeScript web interfaces';
        };
        companyType: 'Software development company';
        description: 'Worked on multiple client products across backend, web and mobile, contributing to application features, APIs and service integrations.';
        period: 'Jul 2020 - Feb 2022';
        role: 'Fullstack JavaScript Developer';
      };
    };
    header: {
      closeMenu: 'Close navigation menu';
      languageSwitcher: {
        label: 'Choose language';
        language: {
          en: 'EN';
          pt: 'PT';
        };
      };
      navigation: {
        about: 'About';
        contact: 'Contact';
        experience: 'Experience';
        projects: 'Projects';
      };
      navigationLabel: 'Primary navigation';
      openMenu: 'Open navigation menu';
    };
    hero: {
      cta: 'View my work';
      description: 'React, TypeScript and frontend experience in the crypto industry.';
      headline: 'Sammuel Reis';
      projects: {
        github: 'GitHub';
        liveProject: 'Live project';
      };
      role: 'Frontend Developer';
      scrollIndicator: 'Scroll to continue';
    };
    projects: {
      action: {
        github: 'GitHub';
        hideDetails: 'Hide details';
        liveProject: 'Live project';
        viewDetails: 'View details';
      };
      cowfunding: {
        description: 'I built Cowfunding as a crowdfunding experience for rural and agricultural initiatives, with campaign discovery, contribution flows and account actions organized around a simple product surface.';
        feature: {
          authentication: 'Authentication and account entry points for contributors';
          campaigns: 'Campaign discovery focused on rural and agricultural projects';
          contributions: 'Contribution flows structured for campaign funding';
        };
        imageAlt: 'Cowfunding project thumbnail';
        summary: 'Crowdfunding platform for rural and agricultural projects.';
        title: 'Cowfunding';
      };
      mainFeatures: 'Main features';
      manaVaultBuilder: {
        description: 'I built ManaVaultBuilder to simplify the creation and management of on-chain vaults, with a focus on asset allocation, real-time portfolio visibility and wallet-based interaction.';
        feature: {
          allocationTracking: 'Real-time portfolio allocation and value tracking';
          customVaults: 'Create and manage custom on-chain vaults with multiple assets';
          oracleData: 'Integrated market data via Chainlink and Redstone oracles';
          walletInteraction: 'Connect and interact with Web3 wallets';
        };
        imageAlt: 'ManaVaultBuilder project thumbnail';
        summary: 'Web3 vault builder for creating and managing on-chain strategies.';
        title: 'ManaVaultBuilder';
      };
      nfEtMatcher: {
        description: 'I built NF_ET Matcher as an NFT collection matcher and analytics interface, combining collection search, live matching flows and wallet-aware interactions in a compact dashboard.';
        feature: {
          collectionSearch: 'Search and inspect NFT collections from a focused interface';
          liveMatching: 'Live matching workflow for comparing collection items';
          walletConnection: 'Wallet connection entry point for Web3 interactions';
        };
        imageAlt: 'NF_ET Matcher project thumbnail';
        summary: 'Real-time NFT collection matcher and analytics platform.';
        title: 'NF_ET Matcher';
      };
      title: 'Projects';
    };
  };
};
